# Keys like URL, DB name, and DB credentials should be provided by the environment.
# They are hardcoded here for practice purposes.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food-delivery-test?createDatabaseIfNotExist=true
    username: joe
    password: "vv44sRUF#NCtu7zKcfR5uYdps6*"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

logging:
  level:
    org:
      hibernate: debug
      hibernate.sql: debug
      springframework:
        web: debug
    com:
      joe:
        abelaziz: debug
